"""idkwhatswrong

Revision ID: 29ddde28817c
Revises: 8f67591fc2e0
Create Date: 2025-05-19 13:34:35.796381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ddde28817c'
down_revision: Union[str, None] = '8f67591fc2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.alter_column('user_actions', 'total',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_actions', 'total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'accounts', type_='unique')
    # ### end Alembic commands ###
